// Generated by CoffeeScript 1.7.1
(function() {
  window.JsonStat = (function() {
    function JsonStat(array) {
      this.collection = array;
    }

    JsonStat.prototype.statByTime = function(options) {
      var condition, key, point, result, result0, result1, time, values, _fn, _i, _len, _ref;
      result0 = [];
      result1 = [];
      condition = options.condition;
      time = options.time;
      key = options.condition.key;
      values = options.condition.values;
      if (options.by === 'day') {
        _ref = this.collection;
        _fn = function(point) {
          var last, tmp;
          if (point[key] === values[0]) {
            last = result0[result0.length - 1];
            if (last === void 0) {
              tmp = {
                t: moment(point[time]).startOf('day').valueOf(),
                count: 0
              };
              result0.push(tmp);
              last = result0[result0.length - 1];
            }
            if (moment(point[time]).isSame(last[time], 'day')) {
              return last.count++;
            } else {
              tmp = {
                t: moment(point[time]).startOf('day').valueOf(),
                count: 1
              };
              return result0.push(tmp);
            }
          } else if (point[key] === values[1]) {
            last = result1[result1.length - 1];
            if (last === void 0) {
              tmp = {
                t: moment(point[time]).startOf('day').valueOf(),
                count: 0
              };
              result1.push(tmp);
              last = result1[result1.length - 1];
            }
            if (moment(point[time]).isSame(last[time], 'day')) {
              return last.count++;
            } else {
              tmp = {
                t: moment(point[time]).startOf('day').valueOf(),
                count: 1
              };
              return result1.push(tmp);
            }
          }
        };
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          point = _ref[_i];
          _fn(point);
        }
        result = [result0, result1];
        return console.log(result);
      } else {
        return alert('Just can count by day');
      }
    };

    JsonStat.prototype.sortCollection = function() {};

    JsonStat.prototype.rangeTime = function(start, end) {};

    JsonStat.prototype.filterByTime = function(options) {};

    return JsonStat;

  })();

}).call(this);
